version: '3.8'

services:
  # ChromaDB for cloud vector database
  chromadb:
    image: chromadb/chroma:latest
    container_name: claude-context-chromadb-cloud
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Optional: Ollama for local embedding models in cloud
  ollama:
    image: ollama/ollama:latest
    container_name: claude-context-ollama-cloud
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: claude-context-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - chromadb
      - ollama
    restart: unless-stopped

volumes:
  chromadb_data:
    driver: local
  ollama_data:
    driver: local
